Improve bash scripts

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# pre-commit git hook
+# GIT Pre-Commit Hook
 #
 # Prerequisites:
 #   gem install puppet-lint puppet
@@ -8,9 +8,18 @@
 #  /path/to/repo/.git/hooks/pre-commit
 #
 # Authors:
+#  Vlad Ghinea
 #  Ronny Roethof
 #  Mattias Geniar <m@ttias.be>
 #  Rob Nelson <rnelson0@gmail.com>
+
+# Immediately exit on errors
+set -euo pipefail
+
+# Load environment
+# shellcheck disable=1090
+. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/../../load" || \
+  . "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/../load" || true
 
 # Add RVM
 # shellcheck disable=1090
@@ -65,6 +74,14 @@ if ! [ -x "$path_to_aws" ]; then
   echo "The AWS CLI binary wasn't found."
   echo "Sorry, I won't allow you to commit without aws cli installed."
   echo "Please install aws cli and try again."
+  exit 1
+fi
+
+path_to_shellcheck=$(command -v shellcheck)
+if ! [ -x "$path_to_shellcheck" ]; then
+  echo "The Shellcheck binary wasn't found."
+  echo "Sorry, I won't allow you to commit without shellcheck installed."
+  echo "Please install shellcheck and try again."
   exit 1
 fi
 
@@ -154,6 +171,20 @@ for file in $(git diff --name-only --cached | grep -E 'cfn\/.*\.(json)'); do
       --template-body "file://${file}"
     if [[ $? -ne 0 ]]; then
       echo "ERROR: Cloudformation syntax validation failed at: $file"
+      syntax_is_bad=1
+    else
+       echo "OK: $file looks valid"
+    fi
+  fi
+done
+echo ""
+
+echo "### Checking if bash syntax is valid ###"
+for file in $(git diff --name-only --cached | grep -E '\.(sh)'); do
+  if [[ -f $file ]]; then
+    shellcheck "$file"
+    if [[ $? -ne 0 ]]; then
+      echo "ERROR: Bash syntax validation failed at: $file"
       syntax_is_bad=1
     else
        echo "OK: $file looks valid"
